FOUNDATIONS: Retrieve All Tables and Their Details
hassanhabib/Standard.AI.Data.EntityIntelligence pull request #32
Opened 2023-07-24 13:52 UTC by mtoncic

Closes #25

2023-07-24 15:10 UTC, glhays commented
@mtoncic Although the commit history naming has been corrected, the actual fail/pass of each test has been bypassed. The first failing test should show it failed then followed by an actual passing. Consider closing the PR, and follow the fail commit, pass commit sequence used by The Standard coding concepts.
Please add the logging to the exceptions to the appropriate tests.
Verify no other calls are missing on several tests please correct.

Image for clarity.

![image](https://github.com/hassanhabib/Standard.AI.Data.EntityIntelligence/assets/42452283/216e40a1-901e-41a6-8812-813c6abe39cd)

2023-07-24 23:23 UTC, mtoncic commented
> @mtoncic Although the commit history naming has been corrected, the actual fail/pass of each test has been bypassed. The first failing test should show it failed then followed by an actual passing. Consider closing the PR, and follow the fail commit, pass commit sequence used by The Standard coding concepts. Please add the logging to the exceptions to the appropriate tests. Verify no other calls are missing on several tests please correct.
> 
> Image for clarity.
> 
> ![image](https://user-images.githubusercontent.com/42452283/255691784-216e40a1-901e-41a6-8812-813c6abe39cd.png)

Not sure what you're talking about. That screenshot is from the previous PR.

2023-07-25 00:32 UTC, glhays commented
> > @mtoncic Although the commit history naming has been corrected, the actual fail/pass of each test has been bypassed. The first failing test should show it failed then followed by an actual passing. Consider closing the PR, and follow the fail commit, pass commit sequence used by The Standard coding concepts. Please add the logging to the exceptions to the appropriate tests. Verify no other calls are missing on several tests please correct.
> > Image for clarity.
> > ![image](https://user-images.githubusercontent.com/42452283/255691784-216e40a1-901e-41a6-8812-813c6abe39cd.png)
> 
> Not sure what you're talking about. That screenshot is from the previous PR.

Yes I know it is, which your new PR does not show a legit commit history other than in name only.
Image was visual clarity only.

2023-07-25 06:27 UTC, hassanhabib commented on Standard.AI.Data.EntityIntelligence/Services/Foundations/Datas/DataService.cs
> +                new()
Use explicit types `new Student` not `new()`

2023-07-25 06:28 UTC, hassanhabib commented on Standard.AI.Data.EntityIntelligence/Services/Foundations/Datas/DataService.cs
> +                    ColumnsMetadata =
Put a new empty line between one-liners and multi-liners

2023-07-25 06:28 UTC, hassanhabib commented on Standard.AI.Data.EntityIntelligence/Services/Foundations/Datas/DataService.cs
> +            return ToTablesMetadata(retrievedTablesColumnsMetadata);
New line above this one.

2023-07-25 06:28 UTC, hassanhabib commented on Standard.AI.Data.EntityIntelligence/Services/Foundations/Datas/DataService.cs
> +            var retrievedTablesColumnsMetadata =
Explicit type if the right side is not clear

2023-07-25 06:30 UTC, hassanhabib commented on Standard.AI.Data.EntityIntelligence/Services/Foundations/Datas/DataService.Exceptions.cs
> +                throw new DataStorageDependencyValidationException(failedDependencyValidationException);
These exceptions names must match the service name.
So `StudentService` will throw `StudentDependencyValidationException`
In this case here - you probably want to say `DataDependencyValidationException` and let the inner describe a bit more what the dependency is and why it's failing so something like `InvalidDataValidationException`

2023-07-25 06:31 UTC, hassanhabib commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Logics.Retrieve.cs
> +                            Environment.NewLine,
You only need one-tab

2023-07-25 06:31 UTC, hassanhabib commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Logics.Retrieve.cs
> +                            Environment.NewLine,
Also define input parameters names

2023-07-28 04:06 UTC, hassanhabib commented on Standard.AI.Data.EntityIntelligence/Services/Foundations/Datas/IDataService.cs
> +        ValueTask<List<TableMetadata>> RetrieveTablesDetailsAsync();
We discussed this. this comment is just a reminder to change the name of the method here to be `RetrieveTableMetadatasAsync()`

2023-07-28 04:08 UTC, hassanhabib commented on Standard.AI.Data.EntityIntelligence/Services/Foundations/Datas/DataService.cs
> +            var groupedColumns =
You must explicitly declare the type of the left side if the right side isn't clear.
https://github.com/hassanhabib/CSharpCodingStandard/blob/master/5.%20Variables.md#do-6

2023-07-28 04:09 UTC, hassanhabib commented on Standard.AI.Data.EntityIntelligence/Services/Foundations/Datas/DataService.cs
> +                new TableMetadata
New line between multi-liners and others.

2023-07-28 04:11 UTC, hassanhabib commented on Standard.AI.Data.EntityIntelligence/Services/Foundations/Datas/DataService.cs
> +                "FROM INFORMATION_SCHEMA.COLUMNS c");
Do you mind changing `c`to something more descriptive such as `column`?

2023-07-28 04:11 UTC, hassanhabib commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Exceptions.Retrieve.cs
> +                new InvalidDataValidationException(invalidArgumentException);
`InvalidDataException`

2023-07-28 04:12 UTC, hassanhabib commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Exceptions.Retrieve.cs
> +            var retrieveTablesDetailsTask = this.dataService.RetrieveTablesDetailsAsync();
Left side type

2023-07-28 04:12 UTC, hassanhabib commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Exceptions.Retrieve.cs
> +                                       retrieveTablesDetailsTask.AsTask);
Just one tab

2023-07-28 04:17 UTC, hukailu commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Exceptions.Retrieve.cs
> +                        invalidOperationDataValidationException);
one tab after above line

2023-07-28 04:17 UTC, hukailu commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Exceptions.Retrieve.cs
> +            var retrieveTablesDetailsTask = this.dataService.RetrieveTablesDetailsAsync();
Concrete type

2023-07-28 04:18 UTC, hukailu commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Exceptions.Retrieve.cs
> +                                       retrieveTablesDetailsTask.AsTask);
one tab after above line

2023-07-28 04:19 UTC, hukailu commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Exceptions.Retrieve.cs
> +            var retrieveTablesDetailsTask = this.dataService.RetrieveTablesDetailsAsync();
same as above

2023-07-28 04:20 UTC, hukailu commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Logics.Retrieve.cs
> +            var query = String.Join(
Concrete types for all the vars in this test

2023-07-28 04:20 UTC, hukailu commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Logics.Retrieve.cs
> +                    foreach (var columnKey in columnsMetadata.Keys)
a new line before foreach

2023-07-28 04:21 UTC, hukailu commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Logics.Retrieve.cs
> +                        tablesColumnsMetadata.Add(
a new line between single liner and multi liner

2023-07-28 04:21 UTC, hukailu commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Logics.Retrieve.cs
> +                    return new TableMetadata
need a new line

2023-07-28 04:21 UTC, hukailu commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Logics.Retrieve.cs
> +                        ColumnsMetadata = columnsMetadata.Keys.Select(key => new ColumnMetadata
a new line here

2023-07-28 04:22 UTC, hukailu commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Logics.Retrieve.cs
> +            dataBrokerMock.Setup(broker => broker.ExecuteQueryAsync<TableColumnMetadata>(query))
push everything after fat arrow to a new line

2023-07-28 04:23 UTC, hukailu commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.cs
> +        private static int GetRandomNumber(int min = 5, int max = 10) =>
Is there a reason to use 5 as min?

2023-07-28 04:24 UTC, hukailu commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.cs
> +
don't need this line

2023-07-28 04:25 UTC, hukailu commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.cs
> +            return new(new(randomSchemaName, randomTableName), columnsDictionary);
can you think of a nicer way this line?

2023-07-28 04:27 UTC, hukailu commented on Standard.AI.Data.EntityIntelligence/Services/Foundations/Datas/DataService.Exceptions.cs
> +        private delegate ValueTask<List<TableMetadata>> ReturningFunction();
Returning List Function

2023-07-28 04:28 UTC, hukailu commented on Standard.AI.Data.EntityIntelligence/Services/Foundations/Datas/IDataService.cs
> +        ValueTask<List<TableMetadata>> RetrieveTablesDetailsAsync();
Return type IEnumerable instead of list?

2023-07-28 05:02 UTC, mtoncic commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.cs
> +        private static int GetRandomNumber(int min = 5, int max = 10) =>
2 to 10 maybe

2023-07-29 00:16 UTC, glhays requested changes

2023-07-29 00:16 UTC, glhays commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Exceptions.Retrieve.cs
> +                    Times.Once);
Missing verification that no other calls have been made.
```suggestion
                   this.data.BrokerMock.VerifyNoOtherCalls();
```

2023-07-29 00:16 UTC, glhays commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Exceptions.Retrieve.cs
> +        public async Task ShouldThrowDependencyExceptionOnSqlException()
Test name is ambiguous, needs to align with the purpose of its specific service.
ShouldThrowSqlDependencyExceptionOnRetrieveIfSqlDependencyExceptionOccursAndLogItAsync()
for example. Remembering you have a 120 character max limit which allows you to shorten if needed, but only enough to bring it below that threshold.

```suggestion
        public async Task ShouldThrowSqlDependencyExceptionOnRetrieveIfSqlDependencyExceptionOccursAndLogItAsync()
```

2023-07-29 00:16 UTC, glhays commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Logics.Retrieve.cs
> +            dataBrokerMock.Setup(broker => broker.ExecuteQueryAsync<TableColumnMetadata>(query))
Be explicit here by using "this"
```suggestion
            this.dataBrokerMock.Setup(broker => broker.ExecuteQueryAsync<TableColumnMetadata>(query))
```

2023-07-29 00:16 UTC, glhays commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Logics.Retrieve.cs
> +            dataBrokerMock.Verify(broker =>
Same here.
```suggestion
            this.dataBrokerMock.Verify(broker =>
```

2023-07-29 00:16 UTC, glhays commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Logics.Retrieve.cs
> +            dataBrokerMock.VerifyNoOtherCalls();
Same here.
```suggestion
            this.dataBrokerMock.VerifyNoOtherCalls();
```

2023-07-29 00:16 UTC, glhays commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Logics.Retrieve.cs
> +                    Times.Once());
Do not need these ()
```suggestion
                    Times.Once);
```

2023-07-29 00:16 UTC, glhays commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Exceptions.Retrieve.cs
> +        }
Verify no other calls on the broker.
```suggestion
            this.dataBrokeMock.VerifyNoOtherCalls();
        }
```

2023-07-29 00:16 UTC, glhays commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Exceptions.Retrieve.cs
> +        }
Same here

```suggestion
            this.dataBrokeMock.VerifyNoOtherCalls();
        }
```

2023-07-29 00:16 UTC, glhays commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Exceptions.Retrieve.cs
> +        public async Task ShouldThrowDependencyExceptionOnSqlException()
@mtoncic Seeing how we are not going to do logging, you can remove the "AndLogIt" part.

2023-07-29 00:16 UTC, glhays commented on Standard.AI.Data.EntityIntelligence/Models/Foundations/Datas/Exceptions/DataDependencyValidationException.cs
> +                  innerException)
Just one tab here.

2023-07-29 00:16 UTC, glhays commented on Standard.AI.Data.EntityIntelligence/Models/Foundations/Datas/Exceptions/DataServiceException.cs
> +                 innerException)
Just one tab here.

2023-07-29 00:16 UTC, glhays commented on Standard.AI.Data.EntityIntelligence/Models/Foundations/Datas/Exceptions/FailedDataDependencyException.cs
> +                  innerException)
Just one tab here.

2023-07-29 00:16 UTC, glhays commented on Standard.AI.Data.EntityIntelligence/Models/Foundations/Datas/Exceptions/FailedDataServiceException.cs
> +                  innerException)
Just one tab here.

2023-07-29 00:16 UTC, glhays commented on Standard.AI.Data.EntityIntelligence/Models/Foundations/Datas/Exceptions/InvalidDataException.cs
> +                  innerException)
Just one tab here.

2023-07-29 00:16 UTC, glhays commented on Standard.AI.Data.EntityIntelligence/Models/Foundations/Datas/Exceptions/InvalidOperationDataException.cs
> +                  innerException)
Just one tab here.

2023-07-29 00:16 UTC, glhays commented on Standard.AI.Data.EntityIntelligence/Models/Foundations/Datas/Exceptions/DataDependencyException.cs
> +                 innerException)
Just one tab here.

2023-07-29 00:16 UTC, glhays commented on Standard.AI.Data.EntityIntelligence/Services/Foundations/Datas/DataService.Exceptions.cs
> +        private static async ValueTask<IEnumerable<TableMetadata>> TryCatch(ReturningTableMetadatasFunction returningTableMetadatasFunction)
Exceeds 120 char rule, suggest breaking to new line.


```suggestion
        private static async ValueTask<IEnumerable<TableMetadata>> TryCatch(
            ReturningTableMetadatasFunction returningTableMetadatasFunction)
```

2023-07-29 00:16 UTC, glhays commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Logics.Retrieve.cs
> +            var randomNumber = GetRandomNumber();
Not used.. Remove

2023-07-29 00:36 UTC, mtoncic commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Exceptions.Retrieve.cs
> +                    Times.Once);
No it's not, it's just below that line

2023-07-29 00:39 UTC, mtoncic commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Logics.Retrieve.cs
> +            var randomNumber = GetRandomNumber();
Nice catch, not sure why VS didn't scream

2023-07-29 00:40 UTC, mtoncic commented on Standard.AI.Data.EntityIntelligence.Tests.Unit/Services/Foundations/Datas/DataServiceTests.Logics.Retrieve.cs
> +                    Times.Once());
Nice catch

2023-07-29 00:41 UTC, mtoncic commented on Standard.AI.Data.EntityIntelligence/Models/Foundations/Datas/Exceptions/DataDependencyException.cs
> +                 innerException)
Aligned with the exceptions in AI/Exceptions

2023-07-29 00:42 UTC, mtoncic commented on Standard.AI.Data.EntityIntelligence/Models/Foundations/Datas/Exceptions/DataDependencyValidationException.cs
> +                  innerException)
Aligned with the exceptions from AI/Exceptions

2023-07-29 03:48 UTC, glhays approved these changes

2023-07-29 03:49 UTC, merged